import React, { createContext, useContext, useEffect, useState } from 'react';
import { I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Updates from 'expo-updates';

const LANGUAGE_STORAGE_KEY = 'kniss_go_language';

export const LANGUAGES = [
  { code: 'en', label: 'English', isRTL: false },
  { code: 'fr', label: 'French', isRTL: false },
  { code: 'ar', label: 'العربية', isRTL: true },
];

// Hand-rolled dictionary covering every screen's UI chrome (titles, buttons,
// labels, messages) plus the small, fully code-controlled enums: property
// type, amenity names, and Sell/Rent. Deliberately NOT covered: listing
// content typed or picked by a seller (title, description, floors,
// documents, finishing, feature chips) — that's data entered once and shown
// as-is to every viewer, the same way a phone number or a display name
// isn't translated, not app chrome. Add a key here whenever a new screen
// needs translated text.
const translations = {
  en: {
    'settings.title': 'Settings',
    'settings.profile': 'User Profile',
    'settings.languages': 'Languages',
    'settings.updatePhone': 'Update Phone Number',
    'settings.updatePassword': 'Update Password',
    'settings.linkedAccounts': 'Linked Accounts',
    'settings.help': 'Help',
    'settings.terms': 'Terms and Conditions',
    'settings.signOut': 'Sign Out',
    'settings.removeAccount': 'Remove My Account',
    'settings.signIn': 'Log in or create an account',
    'settings.signOutConfirmTitle': 'Sign out?',
    'settings.signOutConfirmMessage': 'You can sign back in with your phone number any time.',
    'settings.removeConfirmTitle': 'Remove your account?',
    'settings.removeConfirmMessage': "This permanently deletes your account. It can't be undone.",
    'settings.removeConfirmButton': 'Remove account',
    'common.cancel': 'Cancel',
    'common.confirm': 'Sign Out',
    'languages.title': 'Languages',
    'profile.title': 'Profile',
    'profile.fullName': 'Full Name',
    'profile.phoneNumber': 'Phone Number',
    'profile.save': 'Save',
    'profile.saved': 'Profile updated',

    // Seller Profile tab: the menu and its stack headers. Namespaced
    // separately from settings.* (the buyer tab) since the two screens are
    // different components that may diverge further.
    'sellerProfile.userProfile': 'User Profile',
    'sellerProfile.languages': 'Languages',
    'sellerProfile.updatePhone': 'Update Phone Number',
    'sellerProfile.updatePassword': 'Update Password',
    'sellerProfile.linkedAccounts': 'Linked Accounts',
    'sellerProfile.help': 'Help',
    'sellerProfile.terms': 'Terms and Conditions',
    'sellerProfile.signOut': 'Sign Out',
    'sellerProfile.removeAccount': 'Remove My Account',
    'sellerProfile.signOutConfirmTitle': 'Sign out?',
    'sellerProfile.signOutConfirmMessage': 'You can sign back in with your phone number any time.',
    'sellerProfile.removeConfirmTitle': 'Remove your account?',
    'sellerProfile.removeConfirmMessage':
      "This permanently deletes your account and all your listings. It can't be undone.",
    'sellerProfile.removeConfirmButton': 'Remove account',
    'sellerProfile.editTitle': 'Profile',
    'sellerProfile.updatePhoneTitle': 'Updating phone number',
    'sellerProfile.updatePasswordTitle': 'Updating password',
    'sellerProfile.linkedAccountsTitle': 'Linked accounts',
    'sellerProfile.helpTitle': 'Help & support',
    'sellerProfile.termsTitle': 'Terms and Conditions',

    // Shared atoms used verbatim across otherwise-unrelated screens.
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.tryAgain': 'Try again',
    'common.verify': 'Verify',
    'common.verifying': 'Verifying…',
    'common.resendPrompt': "Didn't get it? Resend code in 0:{seconds}",
    'common.resendCode': 'Resend code',
    'common.devHint': "Dev build — there's no SMS/WhatsApp provider wired up. Check the server terminal for your code.",
    'common.verificationCode': 'Verification code',
    'common.sale': 'Sale',
    'common.rent': 'Rent',
    'common.offline': 'No internet connection',

    // Property type and amenities: small, fixed sets fully controlled by the
    // app, so they translate reliably wherever a property is shown.
    'propertyType.Villa': 'Villa',
    'propertyType.Apartment': 'Apartment',
    'propertyType.Commercial': 'Commercial',
    'propertyType.Land': 'Land',
    'amenity.hospital': 'Hospital',
    'amenity.school': 'School',
    'amenity.supermarket': 'Supermarket',
    'amenity.mosque': 'Mosque',
    'amenity.busStop': 'Bus stop',
    'amenity.gym': 'Gym',
    'amenity.park': 'Park',

    'welcome.headline': 'Stop scrolling distant listings',
    'welcome.subtitle':
      "See what's for sale or rent right where you are — pick your own radius, from a few streets to across the city.",
    'welcome.discover': 'Discover nearby properties',
    'welcome.loginSignup': 'Log in / Sign up',
    'welcome.terms': 'Joining means you agree to our Terms of Use and Privacy Policy.',

    'login.title': 'Already have an account?',
    'login.subtitle': 'Enter your phone number to continue.',
    'login.phoneLabel': 'Phone number',
    'login.phoneHint': 'Enter your 9-digit Algerian number, e.g. 0555 12 34 56.',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': 'Your password',
    'login.forgot': 'Forgot password?',
    'login.submit': 'Log in',
    'login.submitBusy': 'Logging in…',
    'login.or': 'Or',
    'login.google': 'Continue with Google',
    'login.noAccount': "I don't have an account",
    'login.offlineError': 'You’re offline. Connect to the internet to log in.',

    'forgotPassword.phoneTitle': "What's your number?",
    'forgotPassword.phoneSubtitle': "We'll text a code to the phone number on your account so you can set a new password.",

    'accountType.title': 'Are you a buyer or a seller?',
    'accountType.subtitle': "We'll set up your account the right way.",
    'accountType.buyerTitle': 'Buyer',
    'accountType.buyerDescription': 'Save favourites and get noticed by sellers.',
    'accountType.sellerTitle': 'Seller',
    'accountType.sellerDescription': 'Post and manage property listings.',
    'accountType.haveAccount': 'I already have an account',

    'role.title': 'Who are you?',
    'role.subtitle': "We'll show you the right features for your needs.",
    'role.individualTitle': 'Individual',
    'role.individualDescription': 'Post and manage your own property.',
    'role.agencyTitle': 'Agency',
    'role.agencyDescription': 'Manage multiple listings with a verified badge.',
    'role.pitchTitle': 'Real proximity, real revenue',
    'role.pitch1': 'Post in under 3 minutes',
    'role.pitch2': 'Free listings to start',
    'role.pitch3': 'Reach people nearby instantly',
    'role.haveAccount': 'I already have an account',
    'role.switchToBrowsing': 'Switch to browsing',

    'signupPhone.channelSheetTitle': 'Receive your code via',
    'signupPhone.sendWhatsapp': 'Send via WhatsApp',
    'signupPhone.sendSms': 'Send via SMS',
    'signupPhone.title': "What's your number?",
    'signupPhone.subtitle': 'Clients reach you here via call and WhatsApp. We verify with a code first.',
    'signupPhone.submit': 'Continue',
    'signupPhone.submitBusy': 'Sending…',
    'signupPhone.label': 'Phone number (WhatsApp)',
    'signupPhone.hint': 'Enter a 9-digit Algerian number, e.g. 0555 12 34 56.',
    'signupPhone.offlineError': 'You’re offline. Connect to the internet to continue.',

    'signupOtp.title': 'Enter the code',
    'signupOtp.subtitlePhone': 'We sent a 6-digit code to your phone {phone}',
    'signupOtp.subtitleWhatsapp': 'We sent a 6-digit code to your WhatsApp {phone}',
    'signupOtp.changeNumber': 'Change number',

    'signupPassword.title': 'Create a password',
    'signupPassword.subtitle': "You'll use this to sign in going forward.",
    'signupPassword.submit': 'Set password',
    'signupPassword.setLabel': 'Set password',
    'signupPassword.setPlaceholder': 'At least 8 characters',
    'signupPassword.confirmLabel': 'Confirm password',
    'signupPassword.confirmPlaceholder': 'Repeat your password',
    'signupPassword.errorMinLength': 'Use at least {min} characters.',
    'signupPassword.errorMismatch': 'The two passwords don’t match.',

    'signupProfile.title': 'Complete your profile',
    'signupProfile.subtitle': 'This helps us connect you with the right buyers and renters nearby.',
    'signupProfile.submit': 'Continue',
    'signupProfile.submitBusy': 'Creating account…',
    'signupProfile.addAgencyLogo': 'Add agency logo',
    'signupProfile.addProfileImage': 'Add profile image',
    'signupProfile.agencyLogoLabel': 'Agency logo',
    'signupProfile.profileImageLabel': 'Profile image',
    'signupProfile.fullNameLabel': 'Full name',
    'signupProfile.fullNamePlaceholder': 'e.g. Zakaria Lounis',
    'signupProfile.agencyNameLabel': 'Agency name',
    'signupProfile.agencyNamePlaceholder': 'e.g. Kniss Realty',
    'signupProfile.monthlyLabel': 'How many properties do you post each month?',
    'signupProfile.monthlyPlaceholder': '2',
    'signupProfile.termsText': 'I accept the privacy policy & Terms of Service',
    'signupProfile.termsA11y': 'Accept the privacy policy and terms of service',
    'signupProfile.errorPhotoPermission': 'Allow photo library access to add a picture.',
    'signupProfile.offlineError': 'You’re offline. Connect to the internet to finish.',

    'connectGoogle.title': 'Connect Google',
    'connectGoogle.subtitle': 'Sign in faster next time. You can skip this for now.',
    'connectGoogle.google': 'Google',
    'connectGoogle.connect': 'Connect',
    'connectGoogle.connected': 'Connected',
    'connectGoogle.continue': 'Continue',
    'connectGoogle.skip': 'Skip',

    'termsScreen.title': 'Terms and Conditions',
    'termsScreen.body1': '',
    'termsScreen.body2':
      '',

    'radiusPicker.title': "See what's around you",
    'radiusPicker.subtitle': 'Set your radius, up to {max}',
    'radiusPicker.searchAround': 'Search around',
    'radiusPicker.searchRadiusA11y': 'Search radius',
    'radiusPicker.useCurrentLocation': 'Use my current location',
    'radiusPicker.chooseNeighborhood': 'Choose a neighborhood',
    'radiusPicker.neighborhoodA11y': 'Neighborhood',
    'radiusPicker.startExploring': 'Start Exploring',
    'radiusPicker.startExploringA11y': 'Start exploring',

    'scanning.locatingHeadline': 'Finding your position...',
    'scanning.locatingSubtitleNeighborhood': 'Centring the search on {neighborhood}.',
    'scanning.locatingSubtitleGps': 'Getting an exact GPS lock for accurate results.',
    'scanning.scanningHeadline': 'Scanning {radius} around you...',
    'scanning.scanningSubtitleNeighborhood': "Checking what's nearby in {neighborhood}.",
    'scanning.scanningSubtitleGps': "Checking what's nearby, live as you move.",
    'scanning.foundHeadlineOne': 'Found 1 property nearby',
    'scanning.foundHeadlineOther': 'Found {count} properties nearby',
    'scanning.foundSubtitle': 'Opening your results now.',
    'scanning.cancel': 'Cancel',
    'scanning.errorTitle': 'Unable to locate you',
    'scanning.errorLoadFailed': 'Could not load nearby properties. Try again in a moment.',
    'scanning.errorOffline': "You're offline. Reconnect to the internet to scan the area around you.",
    'scanning.errorNeighborhoodGone': "That neighbourhood isn't available anymore.",
    'scanning.errorLocationDenied': 'Allow location access to see what is nearby.',
    'scanning.errorLocationRead': 'Could not read your location. Make sure location is turned on.',
    'scanning.continueTestLocation': 'Continue with a test location',
    'scanning.label': 'finding you properties in [ {place} ]',
    'scanning.nearYou': 'near you',

    'results.nothingWithin': 'Nothing within {radius}',
    'results.tryWidening': 'Try widening your radius from the previous screen.',

    'propertyDetail.boosted': 'Boosted',
    'propertyDetail.postedAgo': 'Posted {days} days ago',
    'propertyDetail.showLess': 'Show less',
    'propertyDetail.more': 'More',
    'propertyDetail.sectionInfo': 'Property information',
    'propertyDetail.type': 'Type',
    'propertyDetail.landArea': 'Land Area',
    'propertyDetail.area': 'Area',
    'propertyDetail.rooms': 'Rooms',
    'propertyDetail.features': 'Features',
    'propertyDetail.utilities': 'Utilities',
    'propertyDetail.floors': 'Floors',
    'propertyDetail.parkingSpots': 'Parking Spots',
    'propertyDetail.parkingSpotsValue': '{count} Spots',
    'propertyDetail.finishing': 'Finishing',
    'propertyDetail.documents': 'Documents',
    'propertyDetail.whereYoullBe': "Where you'll be",
    'propertyDetail.nearbySubtitle': 'Everything nearby in 500 meters.',
    'propertyDetail.close': 'Close',
    'propertyDetail.addFavorite': 'Add to favorites',
    'propertyDetail.removeFavorite': 'Remove from favorites',
    'propertyDetail.viewProfile': 'View {name} profile',
    'propertyDetail.seller': 'seller',
    'propertyDetail.whatsapp': 'WhatsApp',
    'propertyDetail.callNow': 'Call Now',
    'propertyDetail.contactWhatsapp': 'Contact via WhatsApp',

    'propertyCard.areaRooms': '{area} m² · {rooms} rooms',
    'propertyCard.distanceAway': ' · {distance} away',

    'publicProfile.agency': 'Agency',
    'publicProfile.individualSeller': 'Individual seller',
    'publicProfile.seller': 'Seller',
    'publicProfile.buyer': 'Buyer',
    'publicProfile.otherListings': 'Other listings',
    'publicProfile.noOtherListings': 'No other active listings',

    'favorites.emptyTitle': 'No favorites yet',
    'favorites.emptyMessage':
      "Heart a property to save it for later. You'll find all your favorites right here.",
    'favorites.startExploring': 'Start exploring',

    'dashboard.welcomeBack': 'Welcome back',
    'dashboard.defaultName': 'there',
    'dashboard.activeListings': 'Active listings',
    'dashboard.interestedBuyers': 'Interested buyers',
    'dashboard.expiringSoonSection': 'Listings expiring soon',
    'dashboard.nothingExpiring': 'Nothing expiring in the next {days} days.',
    'dashboard.expiringInDays': 'Expiring in {days}d',
    'dashboard.interestedBuyersSection': 'Interested buyers',
    'dashboard.noInterestYet': 'No interest yet — buyers who favourite your listings show up here.',
    'dashboard.interestedIn': 'Interested in {title} · {time}',
    'dashboard.yourProperties': 'Your properties',
    'dashboard.noPropertiesYet': "You haven't posted anything yet.",
    'dashboard.loadErrorTitle': "Couldn't load your dashboard",

    'listingPosted.title': 'Your ad is now live',
    'listingPosted.active': 'Active',
    'listingPosted.currentLocation': 'Current location',
    'listingPosted.favouriteOne': 'favourite',
    'listingPosted.favouriteOther': 'favourites',
    'listingPosted.expiresInOne': 'Expires in {days} day.',
    'listingPosted.expiresInOther': 'Expires in {days} days.',
    'listingPosted.seeAnnouncement': 'See my announcement',
    'listingPosted.returnToProperties': 'Return to my properties',

    'propertyList.heading': 'Your properties',
    'propertyList.countOne': '{count} listing',
    'propertyList.countOther': '{count} listings',
    'propertyList.searchPlaceholder': 'Search your listings',
    'propertyList.filterA11y': 'Filter listings',
    'propertyList.noListingsTitle': 'No listings yet',
    'propertyList.noListingsText': 'Everything you post shows up here to manage.',
    'propertyList.postListing': 'Post a listing',
    'propertyList.nothingMatchesTitle': 'Nothing matches',
    'propertyList.nothingMatchesText': 'No listing fits this search and filter combination.',
    'propertyList.clearSearchFilters': 'Clear search & filters',
    'propertyList.loadErrorTitle': "Couldn't load your listings",
    'propertyList.interestedBuyerOne': 'interested buyer',
    'propertyList.interestedBuyerOther': 'interested buyers',
    'propertyList.statusActive': 'Active',
    'propertyList.statusExpiringSoon': 'Expiring soon',
    'propertyList.statusExpired': 'Expired',
    'propertyList.statusExpiringInDays': 'Expiring in {days}d',
    'propertyList.purposeSell': 'Sell',
    'propertyList.purposeRent': 'Rent',

    'filterSheet.title': 'Filter',
    'filterSheet.close': 'Close filters',
    'filterSheet.propertyType': 'Property type',
    'filterSheet.status': 'Status',
    'filterSheet.purpose': 'Purpose',
    'filterSheet.clearAll': 'Clear all',
    'filterSheet.clearAllA11y': 'Clear all filters',
    'filterSheet.apply': 'Apply',
    'filterSheet.applyA11y': 'Apply filters',

    'addProperty.signInTitle': 'Sign in to post a listing',
    'addProperty.signInMessage':
      "Browsing doesn't need an account — but to put a property on the map you'll need a seller account.",
    'addProperty.createSellerAccount': 'Create a seller account',
    'addProperty.haveAccount': 'I already have an account',
    'addProperty.buyerAccountTitle': 'This is a buyer account',
    'addProperty.buyerAccountMessage':
      "You're signed in as {name}. Buyer accounts can browse and save favourites, but posting listings needs a seller account.",

    'wizard.errorPhotoPermission': 'Allow photo library access to add pictures.',
    'wizard.errorPhotoProcess': 'Could not process one of those photos. Try a different one.',
    'wizard.errorLocationPermission': 'Allow location access to set where this property is.',
    'wizard.errorLocationFailed': 'Could not get your location. Try again in a moment.',
    'wizard.offlineError': 'You’re offline. Connect to the internet to post your listing.',
    'wizard.post': 'Post',
    'wizard.posting': 'Posting…',

    'wizard.listingType.title': 'Sell or rent?',
    'wizard.listingType.subtitle': 'Are you putting this property up for sale or for rent?',

    'wizard.type.title': 'Property type',
    'wizard.type.subtitle': "Pick what you're listing — each type asks for its own details.",

    'wizard.about.title': 'Tell buyers about your property',
    'wizard.about.subtitle': 'The basics buyers scan first.',
    'wizard.about.titleLabel': 'Title',
    'wizard.about.titlePlaceholderVilla': 'e.g. Villa with garden, Hydra',
    'wizard.about.titlePlaceholderApartment': 'e.g. Bright F3, Bab Ezzouar',
    'wizard.about.titlePlaceholderCommercial': 'e.g. Corner shop, Kouba',
    'wizard.about.titlePlaceholderLand': 'e.g. Buildable plot, Birtouta',
    'wizard.about.titlePlaceholderDefault': 'Give your listing a title',
    'wizard.about.descriptionLabel': 'Description',
    'wizard.about.descriptionPlaceholder': 'What makes it stand out?',
    'wizard.about.landAreaLabel': 'Land Area (m²)',
    'wizard.about.builtAreaLabel': 'Built Area (m²)',
    'wizard.about.apartmentAreaLabel': 'Apartment Area (m²)',
    'wizard.about.areaLabel': 'Area (m²)',
    'wizard.about.priceLabel': 'Price (DZD)',
    'wizard.about.negotiabilityLabel': 'Negotiability',
    'wizard.about.negotiableYes': 'Yes, negotiable',
    'wizard.about.negotiableNo': 'No, fixed price',
    'wizard.about.negotiableExchange': 'Exchange accepted',

    'wizard.features.title': 'Property features & documents',
    'wizard.features.subtitle': 'All optional — add what applies.',
    'wizard.features.floorsLabel': 'Number of Floors',
    'wizard.features.apartmentTypeLabel': 'Apartment type',
    'wizard.features.roomsLabel': 'Number of rooms',
    'wizard.features.featuresLabel': 'Property features',
    'wizard.features.utilitiesLabel': 'Utilities',
    'wizard.features.parkingLabel': 'Parking spots',
    'wizard.features.finishingLabel': 'Finishing',
    'wizard.features.documentsLabel': 'Ownership Documents',
    'wizard.features.choose': 'Choose…',

    'wizard.nearby.title': "What's nearby",
    'wizard.nearby.subtitle': 'Everything within about 500 metres of the property.',

    'wizard.photos.title': 'Add property photos',
    'wizard.photos.subtitle': 'Up to {max}. Tap × to remove one.',
    'wizard.photos.removePhoto': 'Remove photo {n}',
    'wizard.photos.addPhotos': 'Add photos',

    'wizard.location.title': 'Location',
    'wizard.location.subtitle': 'Where is the property?',
    'wizard.location.useCurrent': 'Use my current location',
    'wizard.location.chooseNeighborhood': 'Choose a neighborhood',
    'wizard.location.finding': 'Finding your position…',
    'wizard.location.setAt': 'Set — {lat}, {lon}',

    'wizard.review.title': 'Review your listing',
    'wizard.review.subtitle': 'Check everything, then post.',
    'wizard.review.editA11y': 'Edit {section}',
    'wizard.review.listingTypeSection': 'Listing type',
    'wizard.review.for': 'For',
    'wizard.review.propertyTypeSection': 'Property type',
    'wizard.review.typeLabel': 'Type',
    'wizard.review.aboutSection': 'About',
    'wizard.review.titleLabel': 'Title',
    'wizard.review.descriptionLabel': 'Description',
    'wizard.review.landAreaLabel': 'Land area',
    'wizard.review.priceLabel': 'Price',
    'wizard.review.negotiabilityLabel': 'Negotiability',
    'wizard.review.featuresSection': 'Features & documents',
    'wizard.review.floorsLabel': 'Floors',
    'wizard.review.apartmentTypeLabel': 'Apartment type',
    'wizard.review.roomsLabel': 'Rooms',
    'wizard.review.featuresLabel': 'Features',
    'wizard.review.utilitiesLabel': 'Utilities',
    'wizard.review.parkingLabel': 'Parking spots',
    'wizard.review.finishingLabel': 'Finishing',
    'wizard.review.documentsLabel': 'Documents',
    'wizard.review.nearbySection': "What's nearby",
    'wizard.review.nearbyLabel': 'Nearby',
    'wizard.review.noneSelected': 'None selected',
    'wizard.review.photosSection': 'Photos',
    'wizard.review.photosLabel': 'Photos',
    'wizard.review.noneAdded': 'None added',
    'wizard.review.locationSection': 'Location',
    'wizard.review.whereLabel': 'Where',
    'wizard.review.coordinatesLabel': 'Coordinates',
    'wizard.review.currentLocation': 'Current location',
    'wizard.review.builtArea': 'Built area',
    'wizard.review.apartmentArea': 'Apartment area',
    'wizard.review.areaLabel': 'Area',

    'linkedAccounts.title': 'Linked accounts',
    'linkedAccounts.subtitle': 'Manage how you sign in and secure your account.',
    'linkedAccounts.phoneNumber': 'Phone number',
    'linkedAccounts.google': 'Google',
    'linkedAccounts.connected': 'Connected',
    'linkedAccounts.connect': 'Connect',
    'linkedAccounts.connectA11y': 'Connect Google',
    'linkedAccounts.connecting': 'Connecting…',
    'linkedAccounts.note':
      'Sign-in is by phone number and password. Google linking is shown for completeness — this build has no real Google sign-in.',

    'help.title': 'Frequently Asked Questions',
    'help.subtitle': 'Answers to common questions about how Kniss Go works.',
    'help.contactButton': 'WhatsApp contact',
    'help.q1': 'Do I need an account to post a listing?',
    'help.a1':
      'Yes. Browsing is open to everyone with no sign-in, but posting a listing needs a free seller account — Individual or Agency.',
    'help.q2': 'How long does a listing stay active?',
    'help.a2': '30 days from the day you post it. After that it shows as Expired on your Property tab.',
    'help.q3': 'What happens when someone favourites my listing?',
    'help.a3':
      "Their phone number is shared with you as an interested buyer — you'll see it on your dashboard and on that listing. Nothing to unlock, no charge.",
    'help.q4': 'Can I edit or delete a listing after it is live?',
    'help.a4':
      'Not yet — editing and taking down listings is still to come. For now a listing runs until its 30-day expiry.',
    'help.q5': 'How do I change my phone number or password?',
    'help.a5':
      'From Profile → Update Phone Number or Update Password. Both send a 6-digit code to confirm it is you before anything changes.',
    'help.q6': 'Is there any cost to using Kniss Go?',
    'help.a6':
      'No. Posting, favourites and interested-buyer contacts are all free. There are no paid listings, boosts or subscriptions.',
    'help.q7': 'Which buyers see my listing?',
    'help.a7':
      'Buyers search within a radius they pick on the map, centred on where they are. Your listing appears to anyone whose radius reaches its location.',

    'updatePasswordOtp.title': "Confirm it's you",
    'updatePasswordOtp.subtitle':
      'We sent a 6-digit code to your WhatsApp {phone}. Enter it to change your password.',

    'updatePasswordForm.title': 'Update your password',
    'updatePasswordForm.subtitle': 'Choose a new password for signing in.',
    'updatePasswordForm.newPasswordLabel': 'New password',
    'updatePasswordForm.confirmLabel': 'Confirm new password',
    'updatePasswordForm.submit': 'Confirm Password',
    'updatePasswordForm.submitBusy': 'Saving…',
    'updatePasswordForm.errorMinLength': 'Use at least {min} characters.',
    'updatePasswordForm.errorMismatch': 'The two passwords don’t match.',
    'updatePasswordForm.offlineError': 'You’re offline. Connect to the internet to continue.',

    'updatePhone.title': 'Update your phone number',
    'updatePhone.subtitle': 'Enter your current and new phone numbers.',
    'updatePhone.currentLabel': 'Phone Number',
    'updatePhone.newLabel': 'New Phone Number',
    'updatePhone.hint': 'Enter a 9-digit Algerian number, e.g. 0555 12 34 56.',
    'updatePhone.sendWhatsapp': 'Send via WhatsApp',
    'updatePhone.sendSms': 'Send via SMS',
    'updatePhone.sending': 'Sending…',
    'updatePhone.errorSame': 'That is already your number.',
    'updatePhone.offlineError': 'You’re offline. Connect to the internet to continue.',

    'updatePhoneCode.title': 'Enter the code',
    'updatePhoneCode.subtitlePhone': 'We sent a 6-digit code to your phone {phone}',
    'updatePhoneCode.subtitleWhatsapp': 'We sent a 6-digit code to your WhatsApp {phone}',

    'updateSuccess.phoneTitle': 'Phone Number Updated Successfully!',
    'updateSuccess.phoneMessage':
      'Your phone number has been updated. You can now use your new number for account verification and notifications.',
    'updateSuccess.passwordTitle': 'Password Updated Successfully!',
    'updateSuccess.passwordMessage':
      'Your password has been changed. You can now use your new password to log in securely.',
    'updateSuccess.goToSettings': 'Go to settings',

    'editProfile.errorPhotoPermission': 'Allow photo library access to change your picture.',
    'editProfile.changePhoto': 'Change profile photo',
    'editProfile.fullNameLabel': 'Full Name',
    'editProfile.agencyNameLabel': 'Agency Name',
    'editProfile.phoneLabel': 'Phone Number',
    'editProfile.phoneHint': 'Change this from Update Phone Number — it stays verified by code.',
    'editProfile.save': 'Save',
    'editProfile.saving': 'Saving…',
    'editProfile.offlineError': 'You’re offline. Connect to the internet to save.',

    'favoritePrompt.title': 'Create a free account to save properties',
    'favoritePrompt.message':
      'Log in or sign up as a buyer to keep your favourites and pick up where you left off.',
    'favoritePrompt.notNow': 'Not now',
    'favoritePrompt.continue': 'Log in / Sign up',

    'photoGallery.photo': 'Photo',
    'photoGallery.photoOfA11y': 'Photo {index} of {total}',
  },
  fr: {
    'settings.title': 'Paramètres',
    'settings.profile': 'Profil utilisateur',
    'settings.languages': 'Langues',
    'settings.updatePhone': 'Modifier le numéro de téléphone',
    'settings.updatePassword': 'Modifier le mot de passe',
    'settings.linkedAccounts': 'Comptes liés',
    'settings.help': 'Aide',
    'settings.terms': 'Conditions générales',
    'settings.signOut': 'Déconnexion',
    'settings.removeAccount': 'Supprimer mon compte',
    'settings.signIn': 'Se connecter ou créer un compte',
    'settings.signOutConfirmTitle': 'Se déconnecter ?',
    'settings.signOutConfirmMessage': 'Vous pourrez vous reconnecter avec votre numéro à tout moment.',
    'settings.removeConfirmTitle': 'Supprimer votre compte ?',
    'settings.removeConfirmMessage': 'Cela supprime définitivement votre compte. Action irréversible.',
    'settings.removeConfirmButton': 'Supprimer le compte',
    'common.cancel': 'Annuler',
    'common.confirm': 'Déconnexion',
    'languages.title': 'Langues',
    'profile.title': 'Profil',
    'profile.fullName': 'Nom complet',
    'profile.phoneNumber': 'Numéro de téléphone',
    'profile.save': 'Enregistrer',
    'profile.saved': 'Profil mis à jour',

    'sellerProfile.userProfile': 'Profil utilisateur',
    'sellerProfile.languages': 'Langues',
    'sellerProfile.updatePhone': 'Modifier le numéro de téléphone',
    'sellerProfile.updatePassword': 'Modifier le mot de passe',
    'sellerProfile.linkedAccounts': 'Comptes liés',
    'sellerProfile.help': 'Aide',
    'sellerProfile.terms': 'Conditions générales',
    'sellerProfile.signOut': 'Déconnexion',
    'sellerProfile.removeAccount': 'Supprimer mon compte',
    'sellerProfile.signOutConfirmTitle': 'Se déconnecter ?',
    'sellerProfile.signOutConfirmMessage':
      'Vous pourrez vous reconnecter avec votre numéro à tout moment.',
    'sellerProfile.removeConfirmTitle': 'Supprimer votre compte ?',
    'sellerProfile.removeConfirmMessage':
      'Cela supprime définitivement votre compte et toutes vos annonces. Action irréversible.',
    'sellerProfile.removeConfirmButton': 'Supprimer le compte',
    'sellerProfile.editTitle': 'Profil',
    'sellerProfile.updatePhoneTitle': 'Modification du numéro',
    'sellerProfile.updatePasswordTitle': 'Modification du mot de passe',
    'sellerProfile.linkedAccountsTitle': 'Comptes liés',
    'sellerProfile.helpTitle': 'Aide et support',
    'sellerProfile.termsTitle': 'Conditions générales',

    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.tryAgain': 'Réessayer',
    'common.verify': 'Vérifier',
    'common.verifying': 'Vérification…',
    'common.resendPrompt': "Vous n'avez rien reçu ? Renvoyer le code dans 0:{seconds}",
    'common.resendCode': 'Renvoyer le code',
    'common.devHint':
      "Version de développement — aucun fournisseur SMS/WhatsApp n'est branché. Consultez le terminal du serveur pour votre code.",
    'common.verificationCode': 'Code de vérification',
    'common.sale': 'Vente',
    'common.rent': 'Location',
    'common.offline': 'Pas de connexion internet',

    'propertyType.Villa': 'Villa',
    'propertyType.Apartment': 'Appartement',
    'propertyType.Commercial': 'Local commercial',
    'propertyType.Land': 'Terrain',
    'amenity.hospital': 'Hôpital',
    'amenity.school': 'École',
    'amenity.supermarket': 'Supermarché',
    'amenity.mosque': 'Mosquée',
    'amenity.busStop': 'Arrêt de bus',
    'amenity.gym': 'Salle de sport',
    'amenity.park': 'Parc',

    'welcome.headline': 'Arrêtez de parcourir des annonces lointaines',
    'welcome.subtitle':
      "Découvrez ce qui est à vendre ou à louer là où vous êtes — choisissez votre propre rayon, de quelques rues à toute la ville.",
    'welcome.discover': 'Découvrir les biens à proximité',
    'welcome.loginSignup': 'Connexion / Inscription',
    'welcome.terms': "En rejoignant l'application, vous acceptez nos Conditions d'utilisation et notre Politique de confidentialité.",

    'login.title': 'Vous avez déjà un compte ?',
    'login.subtitle': 'Entrez votre numéro de téléphone pour continuer.',
    'login.phoneLabel': 'Numéro de téléphone',
    'login.phoneHint': 'Entrez votre numéro algérien à 9 chiffres, ex. 0555 12 34 56.',
    'login.passwordLabel': 'Mot de passe',
    'login.passwordPlaceholder': 'Votre mot de passe',
    'login.forgot': 'Mot de passe oublié ?',
    'login.submit': 'Se connecter',
    'login.submitBusy': 'Connexion…',
    'login.or': 'Ou',
    'login.google': 'Continuer avec Google',
    'login.noAccount': "Je n'ai pas de compte",
    'login.offlineError': 'Vous êtes hors ligne. Connectez-vous à internet pour vous connecter.',

    'forgotPassword.phoneTitle': 'Quel est votre numéro ?',
    'forgotPassword.phoneSubtitle':
      'Nous enverrons un code par SMS au numéro de votre compte pour que vous puissiez définir un nouveau mot de passe.',

    'accountType.title': 'Êtes-vous acheteur ou vendeur ?',
    'accountType.subtitle': 'Nous allons configurer votre compte comme il faut.',
    'accountType.buyerTitle': 'Acheteur',
    'accountType.buyerDescription': 'Enregistrez des favoris et faites-vous remarquer par les vendeurs.',
    'accountType.sellerTitle': 'Vendeur',
    'accountType.sellerDescription': 'Publiez et gérez des annonces immobilières.',
    'accountType.haveAccount': "J'ai déjà un compte",

    'role.title': 'Qui êtes-vous ?',
    'role.subtitle': 'Nous vous montrerons les fonctionnalités adaptées à vos besoins.',
    'role.individualTitle': 'Particulier',
    'role.individualDescription': 'Publiez et gérez votre propre bien.',
    'role.agencyTitle': 'Agence',
    'role.agencyDescription': 'Gérez plusieurs annonces avec un badge vérifié.',
    'role.pitchTitle': 'Vraie proximité, vrais revenus',
    'role.pitch1': 'Publiez en moins de 3 minutes',
    'role.pitch2': 'Annonces gratuites pour commencer',
    'role.pitch3': 'Touchez des personnes à proximité instantanément',
    'role.haveAccount': "J'ai déjà un compte",
    'role.switchToBrowsing': 'Passer à la navigation',

    'signupPhone.channelSheetTitle': 'Recevoir votre code par',
    'signupPhone.sendWhatsapp': 'Envoyer par WhatsApp',
    'signupPhone.sendSms': 'Envoyer par SMS',
    'signupPhone.title': 'Quel est votre numéro ?',
    'signupPhone.subtitle':
      'Les clients vous contactent ici par appel et WhatsApp. Nous vérifions d’abord avec un code.',
    'signupPhone.submit': 'Continuer',
    'signupPhone.submitBusy': 'Envoi…',
    'signupPhone.label': 'Numéro de téléphone (WhatsApp)',
    'signupPhone.hint': 'Entrez un numéro algérien à 9 chiffres, ex. 0555 12 34 56.',
    'signupPhone.offlineError': 'Vous êtes hors ligne. Connectez-vous à internet pour continuer.',

    'signupOtp.title': 'Entrez le code',
    'signupOtp.subtitlePhone': 'Nous avons envoyé un code à 6 chiffres à votre téléphone {phone}',
    'signupOtp.subtitleWhatsapp': 'Nous avons envoyé un code à 6 chiffres à votre WhatsApp {phone}',
    'signupOtp.changeNumber': 'Changer de numéro',

    'signupPassword.title': 'Créez un mot de passe',
    'signupPassword.subtitle': 'Vous l’utiliserez pour vous connecter par la suite.',
    'signupPassword.submit': 'Définir le mot de passe',
    'signupPassword.setLabel': 'Définir le mot de passe',
    'signupPassword.setPlaceholder': 'Au moins 8 caractères',
    'signupPassword.confirmLabel': 'Confirmer le mot de passe',
    'signupPassword.confirmPlaceholder': 'Répétez votre mot de passe',
    'signupPassword.errorMinLength': 'Utilisez au moins {min} caractères.',
    'signupPassword.errorMismatch': 'Les deux mots de passe ne correspondent pas.',

    'signupProfile.title': 'Complétez votre profil',
    'signupProfile.subtitle': 'Cela nous aide à vous mettre en relation avec les bons acheteurs et locataires à proximité.',
    'signupProfile.submit': 'Continuer',
    'signupProfile.submitBusy': 'Création du compte…',
    'signupProfile.addAgencyLogo': "Ajouter le logo de l'agence",
    'signupProfile.addProfileImage': 'Ajouter une photo de profil',
    'signupProfile.agencyLogoLabel': "Logo de l'agence",
    'signupProfile.profileImageLabel': 'Photo de profil',
    'signupProfile.fullNameLabel': 'Nom complet',
    'signupProfile.fullNamePlaceholder': 'ex. Zakaria Lounis',
    'signupProfile.agencyNameLabel': "Nom de l'agence",
    'signupProfile.agencyNamePlaceholder': 'ex. Kniss Realty',
    'signupProfile.monthlyLabel': 'Combien de biens publiez-vous chaque mois ?',
    'signupProfile.monthlyPlaceholder': '2',
    'signupProfile.termsText': "J'accepte la politique de confidentialité et les Conditions d'utilisation",
    'signupProfile.termsA11y': "Accepter la politique de confidentialité et les conditions d'utilisation",
    'signupProfile.errorPhotoPermission': "Autorisez l'accès à la photothèque pour ajouter une image.",
    'signupProfile.offlineError': 'Vous êtes hors ligne. Connectez-vous à internet pour terminer.',

    'connectGoogle.title': 'Connecter Google',
    'connectGoogle.subtitle': 'Connectez-vous plus vite la prochaine fois. Vous pouvez passer cette étape pour l’instant.',
    'connectGoogle.google': 'Google',
    'connectGoogle.connect': 'Connecter',
    'connectGoogle.connected': 'Connecté',
    'connectGoogle.continue': 'Continuer',
    'connectGoogle.skip': 'Passer',

    'termsScreen.title': 'Conditions générales',
    'termsScreen.body1': "Les conditions générales complètes de Kniss Go seront publiées ici.",
    'termsScreen.body2':
      "Cette application est un projet étudiant réalisé pour le module CM3050 Mobile Development de l'University of London. Ce n'est pas un service commercial actif, elle ne collecte aucun paiement et ne stocke les comptes et annonces que sur un serveur de développement local.",

    'radiusPicker.title': 'Découvrez ce qui vous entoure',
    'radiusPicker.subtitle': "Définissez votre rayon, jusqu'à {max}",
    'radiusPicker.searchAround': 'Rechercher autour de',
    'radiusPicker.searchRadiusA11y': 'Rayon de recherche',
    'radiusPicker.useCurrentLocation': 'Utiliser ma position actuelle',
    'radiusPicker.chooseNeighborhood': 'Choisir un quartier',
    'radiusPicker.neighborhoodA11y': 'Quartier',
    'radiusPicker.startExploring': 'Commencer la recherche',
    'radiusPicker.startExploringA11y': 'Commencer la recherche',

    'scanning.locatingHeadline': 'Recherche de votre position...',
    'scanning.locatingSubtitleNeighborhood': 'Centrage de la recherche sur {neighborhood}.',
    'scanning.locatingSubtitleGps': 'Obtention d’un signal GPS précis pour des résultats fiables.',
    'scanning.scanningHeadline': 'Analyse de {radius} autour de vous...',
    'scanning.scanningSubtitleNeighborhood': 'Vérification de ce qui se trouve à {neighborhood}.',
    'scanning.scanningSubtitleGps': 'Vérification de ce qu’il y a à proximité, en temps réel.',
    'scanning.foundHeadlineOne': '1 bien trouvé à proximité',
    'scanning.foundHeadlineOther': '{count} biens trouvés à proximité',
    'scanning.foundSubtitle': 'Ouverture de vos résultats...',
    'scanning.cancel': 'Annuler',
    'scanning.errorTitle': 'Impossible de vous localiser',
    'scanning.errorLoadFailed': 'Impossible de charger les biens à proximité. Réessayez dans un instant.',
    'scanning.errorOffline': "Vous êtes hors ligne. Reconnectez-vous à internet pour analyser la zone autour de vous.",
    'scanning.errorNeighborhoodGone': "Ce quartier n'est plus disponible.",
    'scanning.errorLocationDenied': "Autorisez l'accès à la position pour voir ce qui se trouve à proximité.",
    'scanning.errorLocationRead': 'Impossible de lire votre position. Vérifiez que la localisation est activée.',
    'scanning.continueTestLocation': 'Continuer avec une position de test',
    'scanning.label': 'recherche de biens [ {place} ]',
    'scanning.nearYou': 'près de vous',

    'results.nothingWithin': 'Rien dans un rayon de {radius}',
    'results.tryWidening': "Essayez d'élargir votre rayon depuis l'écran précédent.",

    'propertyDetail.boosted': 'Boosté',
    'propertyDetail.postedAgo': 'Publié il y a {days} jours',
    'propertyDetail.showLess': 'Afficher moins',
    'propertyDetail.more': 'Plus',
    'propertyDetail.sectionInfo': 'Informations sur le bien',
    'propertyDetail.type': 'Type',
    'propertyDetail.landArea': 'Superficie du terrain',
    'propertyDetail.area': 'Superficie',
    'propertyDetail.rooms': 'Pièces',
    'propertyDetail.features': 'Caractéristiques',
    'propertyDetail.utilities': 'Réseaux',
    'propertyDetail.floors': 'Étages',
    'propertyDetail.parkingSpots': 'Places de parking',
    'propertyDetail.parkingSpotsValue': '{count} places',
    'propertyDetail.finishing': 'Finition',
    'propertyDetail.documents': 'Documents',
    'propertyDetail.whereYoullBe': 'Où vous serez',
    'propertyDetail.nearbySubtitle': 'Tout ce qui se trouve à moins de 500 mètres.',
    'propertyDetail.close': 'Fermer',
    'propertyDetail.addFavorite': 'Ajouter aux favoris',
    'propertyDetail.removeFavorite': 'Retirer des favoris',
    'propertyDetail.viewProfile': 'Voir le profil de {name}',
    'propertyDetail.seller': 'vendeur',
    'propertyDetail.whatsapp': 'WhatsApp',
    'propertyDetail.callNow': 'Appeler',
    'propertyDetail.contactWhatsapp': 'Contacter via WhatsApp',

    'propertyCard.areaRooms': '{area} m² · {rooms} pièces',
    'propertyCard.distanceAway': ' · à {distance}',

    'publicProfile.agency': 'Agence',
    'publicProfile.individualSeller': 'Vendeur particulier',
    'publicProfile.seller': 'Vendeur',
    'publicProfile.buyer': 'Acheteur',
    'publicProfile.otherListings': 'Autres annonces',
    'publicProfile.noOtherListings': 'Aucune autre annonce active',

    'favorites.emptyTitle': 'Aucun favori pour le moment',
    'favorites.emptyMessage':
      'Ajoutez un bien en favori pour le retrouver plus tard. Vous retrouverez tous vos favoris ici.',
    'favorites.startExploring': 'Commencer la recherche',

    'dashboard.welcomeBack': 'Bon retour',
    'dashboard.defaultName': '',
    'dashboard.activeListings': 'Annonces actives',
    'dashboard.interestedBuyers': 'Acheteurs intéressés',
    'dashboard.expiringSoonSection': 'Annonces bientôt expirées',
    'dashboard.nothingExpiring': "Rien n'expire dans les {days} prochains jours.",
    'dashboard.expiringInDays': 'Expire dans {days} j',
    'dashboard.interestedBuyersSection': 'Acheteurs intéressés',
    'dashboard.noInterestYet': "Aucun intérêt pour l'instant — les acheteurs qui mettent vos annonces en favori apparaîtront ici.",
    'dashboard.interestedIn': 'Intéressé par {title} · {time}',
    'dashboard.yourProperties': 'Vos biens',
    'dashboard.noPropertiesYet': "Vous n'avez encore rien publié.",
    'dashboard.loadErrorTitle': 'Impossible de charger votre tableau de bord',

    'listingPosted.title': 'Votre annonce est en ligne',
    'listingPosted.active': 'Active',
    'listingPosted.currentLocation': 'Position actuelle',
    'listingPosted.favouriteOne': 'favori',
    'listingPosted.favouriteOther': 'favoris',
    'listingPosted.expiresInOne': 'Expire dans {days} jour.',
    'listingPosted.expiresInOther': 'Expire dans {days} jours.',
    'listingPosted.seeAnnouncement': 'Voir mon annonce',
    'listingPosted.returnToProperties': 'Retour à mes biens',

    'propertyList.heading': 'Vos biens',
    'propertyList.countOne': '{count} annonce',
    'propertyList.countOther': '{count} annonces',
    'propertyList.searchPlaceholder': 'Rechercher dans vos annonces',
    'propertyList.filterA11y': 'Filtrer les annonces',
    'propertyList.noListingsTitle': 'Aucune annonce pour le moment',
    'propertyList.noListingsText': 'Tout ce que vous publiez apparaît ici pour être géré.',
    'propertyList.postListing': 'Publier une annonce',
    'propertyList.nothingMatchesTitle': 'Aucun résultat',
    'propertyList.nothingMatchesText': 'Aucune annonce ne correspond à cette recherche et ces filtres.',
    'propertyList.clearSearchFilters': 'Effacer la recherche et les filtres',
    'propertyList.loadErrorTitle': 'Impossible de charger vos annonces',
    'propertyList.interestedBuyerOne': 'acheteur intéressé',
    'propertyList.interestedBuyerOther': 'acheteurs intéressés',
    'propertyList.statusActive': 'Active',
    'propertyList.statusExpiringSoon': 'Bientôt expirée',
    'propertyList.statusExpired': 'Expirée',
    'propertyList.statusExpiringInDays': 'Expire dans {days} j',
    'propertyList.purposeSell': 'Vente',
    'propertyList.purposeRent': 'Location',

    'filterSheet.title': 'Filtrer',
    'filterSheet.close': 'Fermer les filtres',
    'filterSheet.propertyType': 'Type de bien',
    'filterSheet.status': 'Statut',
    'filterSheet.purpose': 'Objectif',
    'filterSheet.clearAll': 'Tout effacer',
    'filterSheet.clearAllA11y': 'Effacer tous les filtres',
    'filterSheet.apply': 'Appliquer',
    'filterSheet.applyA11y': 'Appliquer les filtres',

    'addProperty.signInTitle': 'Connectez-vous pour publier une annonce',
    'addProperty.signInMessage':
      "Naviguer ne nécessite pas de compte — mais pour publier un bien, il vous faut un compte vendeur.",
    'addProperty.createSellerAccount': 'Créer un compte vendeur',
    'addProperty.haveAccount': "J'ai déjà un compte",
    'addProperty.buyerAccountTitle': "Ceci est un compte acheteur",
    'addProperty.buyerAccountMessage':
      "Vous êtes connecté en tant que {name}. Les comptes acheteur peuvent naviguer et enregistrer des favoris, mais publier des annonces nécessite un compte vendeur.",

    'wizard.errorPhotoPermission': "Autorisez l'accès à la photothèque pour ajouter des photos.",
    'wizard.errorPhotoProcess': "Impossible de traiter l'une de ces photos. Essayez-en une autre.",
    'wizard.errorLocationPermission': "Autorisez l'accès à la position pour indiquer où se trouve ce bien.",
    'wizard.errorLocationFailed': 'Impossible d’obtenir votre position. Réessayez dans un instant.',
    'wizard.offlineError': 'Vous êtes hors ligne. Connectez-vous à internet pour publier votre annonce.',
    'wizard.post': 'Publier',
    'wizard.posting': 'Publication…',

    'wizard.listingType.title': 'Vente ou location ?',
    'wizard.listingType.subtitle': 'Mettez-vous ce bien en vente ou en location ?',

    'wizard.type.title': 'Type de bien',
    'wizard.type.subtitle': 'Choisissez ce que vous publiez — chaque type demande ses propres détails.',

    'wizard.about.title': 'Parlez de votre bien aux acheteurs',
    'wizard.about.subtitle': "Les informations essentielles que les acheteurs regardent d'abord.",
    'wizard.about.titleLabel': 'Titre',
    'wizard.about.titlePlaceholderVilla': 'ex. Villa avec jardin, Hydra',
    'wizard.about.titlePlaceholderApartment': 'ex. F3 lumineux, Bab Ezzouar',
    'wizard.about.titlePlaceholderCommercial': 'ex. Local d’angle, Kouba',
    'wizard.about.titlePlaceholderLand': 'ex. Terrain constructible, Birtouta',
    'wizard.about.titlePlaceholderDefault': 'Donnez un titre à votre annonce',
    'wizard.about.descriptionLabel': 'Description',
    'wizard.about.descriptionPlaceholder': "Qu'est-ce qui le rend unique ?",
    'wizard.about.landAreaLabel': 'Superficie du terrain (m²)',
    'wizard.about.builtAreaLabel': 'Superficie bâtie (m²)',
    'wizard.about.apartmentAreaLabel': "Superficie de l'appartement (m²)",
    'wizard.about.areaLabel': 'Superficie (m²)',
    'wizard.about.priceLabel': 'Prix (DZD)',
    'wizard.about.negotiabilityLabel': 'Négociabilité',
    'wizard.about.negotiableYes': 'Oui, négociable',
    'wizard.about.negotiableNo': 'Non, prix fixe',
    'wizard.about.negotiableExchange': 'Échange accepté',

    'wizard.features.title': 'Caractéristiques et documents du bien',
    'wizard.features.subtitle': 'Tout est facultatif — ajoutez ce qui s’applique.',
    'wizard.features.floorsLabel': "Nombre d'étages",
    'wizard.features.apartmentTypeLabel': "Type d'appartement",
    'wizard.features.roomsLabel': 'Nombre de pièces',
    'wizard.features.featuresLabel': 'Caractéristiques du bien',
    'wizard.features.utilitiesLabel': 'Réseaux',
    'wizard.features.parkingLabel': 'Places de parking',
    'wizard.features.finishingLabel': 'Finition',
    'wizard.features.documentsLabel': 'Documents de propriété',
    'wizard.features.choose': 'Choisir…',

    'wizard.nearby.title': 'Ce qu’il y a à proximité',
    'wizard.nearby.subtitle': 'Tout ce qui se trouve à environ 500 mètres du bien.',

    'wizard.photos.title': 'Ajouter des photos du bien',
    'wizard.photos.subtitle': "Jusqu'à {max}. Appuyez sur × pour en retirer une.",
    'wizard.photos.removePhoto': 'Retirer la photo {n}',
    'wizard.photos.addPhotos': 'Ajouter des photos',

    'wizard.location.title': 'Emplacement',
    'wizard.location.subtitle': 'Où se trouve le bien ?',
    'wizard.location.useCurrent': 'Utiliser ma position actuelle',
    'wizard.location.chooseNeighborhood': 'Choisir un quartier',
    'wizard.location.finding': 'Recherche de votre position…',
    'wizard.location.setAt': 'Défini — {lat}, {lon}',

    'wizard.review.title': 'Vérifiez votre annonce',
    'wizard.review.subtitle': 'Vérifiez tout, puis publiez.',
    'wizard.review.editA11y': 'Modifier {section}',
    'wizard.review.listingTypeSection': "Type d'annonce",
    'wizard.review.for': 'Pour',
    'wizard.review.propertyTypeSection': 'Type de bien',
    'wizard.review.typeLabel': 'Type',
    'wizard.review.aboutSection': 'À propos',
    'wizard.review.titleLabel': 'Titre',
    'wizard.review.descriptionLabel': 'Description',
    'wizard.review.landAreaLabel': 'Superficie du terrain',
    'wizard.review.priceLabel': 'Prix',
    'wizard.review.negotiabilityLabel': 'Négociabilité',
    'wizard.review.featuresSection': 'Caractéristiques et documents',
    'wizard.review.floorsLabel': 'Étages',
    'wizard.review.apartmentTypeLabel': "Type d'appartement",
    'wizard.review.roomsLabel': 'Pièces',
    'wizard.review.featuresLabel': 'Caractéristiques',
    'wizard.review.utilitiesLabel': 'Réseaux',
    'wizard.review.parkingLabel': 'Places de parking',
    'wizard.review.finishingLabel': 'Finition',
    'wizard.review.documentsLabel': 'Documents',
    'wizard.review.nearbySection': 'Ce qu’il y a à proximité',
    'wizard.review.nearbyLabel': 'À proximité',
    'wizard.review.noneSelected': 'Aucun sélectionné',
    'wizard.review.photosSection': 'Photos',
    'wizard.review.photosLabel': 'Photos',
    'wizard.review.noneAdded': 'Aucune ajoutée',
    'wizard.review.locationSection': 'Emplacement',
    'wizard.review.whereLabel': 'Où',
    'wizard.review.coordinatesLabel': 'Coordonnées',
    'wizard.review.currentLocation': 'Position actuelle',
    'wizard.review.builtArea': 'Superficie bâtie',
    'wizard.review.apartmentArea': "Superficie de l'appartement",
    'wizard.review.areaLabel': 'Superficie',

    'linkedAccounts.title': 'Comptes liés',
    'linkedAccounts.subtitle': 'Gérez la manière dont vous vous connectez et sécurisez votre compte.',
    'linkedAccounts.phoneNumber': 'Numéro de téléphone',
    'linkedAccounts.google': 'Google',
    'linkedAccounts.connected': 'Connecté',
    'linkedAccounts.connect': 'Connecter',
    'linkedAccounts.connectA11y': 'Connecter Google',
    'linkedAccounts.connecting': 'Connexion…',
    'linkedAccounts.note':
      "La connexion se fait par numéro de téléphone et mot de passe. La liaison Google est affichée à titre indicatif — cette version n'a pas de vraie connexion Google.",

    'help.title': 'Foire aux questions',
    'help.subtitle': 'Réponses aux questions courantes sur le fonctionnement de Kniss Go.',
    'help.contactButton': 'Contact WhatsApp',
    'help.q1': "Ai-je besoin d'un compte pour publier une annonce ?",
    'help.a1':
      "Oui. La navigation est ouverte à tous sans connexion, mais publier une annonce nécessite un compte vendeur gratuit — Particulier ou Agence.",
    'help.q2': 'Combien de temps une annonce reste-t-elle active ?',
    'help.a2': "30 jours à partir de sa publication. Ensuite, elle apparaît comme Expirée dans votre onglet Biens.",
    'help.q3': "Que se passe-t-il quand quelqu'un met mon annonce en favori ?",
    'help.a3':
      "Son numéro de téléphone vous est communiqué comme acheteur intéressé — vous le verrez sur votre tableau de bord et sur cette annonce. Rien à débloquer, aucun frais.",
    'help.q4': 'Puis-je modifier ou supprimer une annonce une fois publiée ?',
    'help.a4':
      "Pas encore — la modification et le retrait des annonces arriveront plus tard. Pour l'instant, une annonce reste active jusqu'à ses 30 jours.",
    'help.q5': 'Comment changer mon numéro de téléphone ou mon mot de passe ?',
    'help.a5':
      "Depuis Profil → Modifier le numéro de téléphone ou Modifier le mot de passe. Les deux envoient un code à 6 chiffres pour confirmer votre identité avant tout changement.",
    'help.q6': "Y a-t-il un coût à utiliser Kniss Go ?",
    'help.a6':
      "Non. La publication, les favoris et les contacts d'acheteurs intéressés sont tous gratuits. Il n'y a ni annonces payantes, ni boosts, ni abonnements.",
    'help.q7': 'Quels acheteurs voient mon annonce ?',
    'help.a7':
      "Les acheteurs recherchent dans un rayon qu'ils choisissent, centré sur leur position. Votre annonce apparaît à quiconque dont le rayon atteint son emplacement.",

    'updatePasswordOtp.title': "Confirmez que c'est bien vous",
    'updatePasswordOtp.subtitle':
      'Nous avons envoyé un code à 6 chiffres à votre WhatsApp {phone}. Entrez-le pour changer votre mot de passe.',

    'updatePasswordForm.title': 'Modifier votre mot de passe',
    'updatePasswordForm.subtitle': 'Choisissez un nouveau mot de passe pour vous connecter.',
    'updatePasswordForm.newPasswordLabel': 'Nouveau mot de passe',
    'updatePasswordForm.confirmLabel': 'Confirmer le nouveau mot de passe',
    'updatePasswordForm.submit': 'Confirmer le mot de passe',
    'updatePasswordForm.submitBusy': 'Enregistrement…',
    'updatePasswordForm.errorMinLength': 'Utilisez au moins {min} caractères.',
    'updatePasswordForm.errorMismatch': 'Les deux mots de passe ne correspondent pas.',
    'updatePasswordForm.offlineError': 'Vous êtes hors ligne. Connectez-vous à internet pour continuer.',

    'updatePhone.title': 'Modifier votre numéro de téléphone',
    'updatePhone.subtitle': 'Entrez votre numéro actuel et votre nouveau numéro.',
    'updatePhone.currentLabel': 'Numéro de téléphone',
    'updatePhone.newLabel': 'Nouveau numéro de téléphone',
    'updatePhone.hint': 'Entrez un numéro algérien à 9 chiffres, ex. 0555 12 34 56.',
    'updatePhone.sendWhatsapp': 'Envoyer par WhatsApp',
    'updatePhone.sendSms': 'Envoyer par SMS',
    'updatePhone.sending': 'Envoi…',
    'updatePhone.errorSame': "C'est déjà votre numéro actuel.",
    'updatePhone.offlineError': 'Vous êtes hors ligne. Connectez-vous à internet pour continuer.',

    'updatePhoneCode.title': 'Entrez le code',
    'updatePhoneCode.subtitlePhone': 'Nous avons envoyé un code à 6 chiffres à votre téléphone {phone}',
    'updatePhoneCode.subtitleWhatsapp': 'Nous avons envoyé un code à 6 chiffres à votre WhatsApp {phone}',

    'updateSuccess.phoneTitle': 'Numéro de téléphone mis à jour !',
    'updateSuccess.phoneMessage':
      'Votre numéro de téléphone a été mis à jour. Vous pouvez désormais l’utiliser pour la vérification de compte et les notifications.',
    'updateSuccess.passwordTitle': 'Mot de passe mis à jour !',
    'updateSuccess.passwordMessage':
      'Votre mot de passe a été modifié. Vous pouvez désormais l’utiliser pour vous connecter en toute sécurité.',
    'updateSuccess.goToSettings': 'Aller aux paramètres',

    'editProfile.errorPhotoPermission': "Autorisez l'accès à la photothèque pour changer votre photo.",
    'editProfile.changePhoto': 'Changer la photo de profil',
    'editProfile.fullNameLabel': 'Nom complet',
    'editProfile.agencyNameLabel': "Nom de l'agence",
    'editProfile.phoneLabel': 'Numéro de téléphone',
    'editProfile.phoneHint': 'Modifiez-le depuis Modifier le numéro de téléphone — il reste vérifié par code.',
    'editProfile.save': 'Enregistrer',
    'editProfile.saving': 'Enregistrement…',
    'editProfile.offlineError': 'Vous êtes hors ligne. Connectez-vous à internet pour enregistrer.',

    'favoritePrompt.title': 'Créez un compte gratuit pour enregistrer des biens',
    'favoritePrompt.message':
      'Connectez-vous ou inscrivez-vous en tant qu’acheteur pour conserver vos favoris et reprendre où vous en étiez.',
    'favoritePrompt.notNow': 'Pas maintenant',
    'favoritePrompt.continue': 'Connexion / Inscription',

    'photoGallery.photo': 'Photo',
    'photoGallery.photoOfA11y': 'Photo {index} sur {total}',
  },
  ar: {
    'settings.title': 'الإعدادات',
    'settings.profile': 'الملف الشخصي',
    'settings.languages': 'اللغات',
    'settings.updatePhone': 'تحديث رقم الهاتف',
    'settings.updatePassword': 'تحديث كلمة المرور',
    'settings.linkedAccounts': 'الحسابات المرتبطة',
    'settings.help': 'المساعدة',
    'settings.terms': 'الشروط والأحكام',
    'settings.signOut': 'تسجيل الخروج',
    'settings.removeAccount': 'حذف حسابي',
    'settings.signIn': 'تسجيل الدخول أو إنشاء حساب',
    'settings.signOutConfirmTitle': 'تسجيل الخروج؟',
    'settings.signOutConfirmMessage': 'يمكنك تسجيل الدخول مجددًا برقم هاتفك في أي وقت.',
    'settings.removeConfirmTitle': 'حذف حسابك؟',
    'settings.removeConfirmMessage': 'سيؤدي هذا إلى حذف حسابك نهائيًا. لا يمكن التراجع عن هذا.',
    'settings.removeConfirmButton': 'حذف الحساب',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تسجيل الخروج',
    'languages.title': 'اللغات',
    'profile.title': 'الملف الشخصي',
    'profile.fullName': 'الاسم الكامل',
    'profile.phoneNumber': 'رقم الهاتف',
    'profile.save': 'حفظ',
    'profile.saved': 'تم تحديث الملف الشخصي',

    'sellerProfile.userProfile': 'الملف الشخصي',
    'sellerProfile.languages': 'اللغات',
    'sellerProfile.updatePhone': 'تحديث رقم الهاتف',
    'sellerProfile.updatePassword': 'تحديث كلمة المرور',
    'sellerProfile.linkedAccounts': 'الحسابات المرتبطة',
    'sellerProfile.help': 'المساعدة',
    'sellerProfile.terms': 'الشروط والأحكام',
    'sellerProfile.signOut': 'تسجيل الخروج',
    'sellerProfile.removeAccount': 'حذف حسابي',
    'sellerProfile.signOutConfirmTitle': 'تسجيل الخروج؟',
    'sellerProfile.signOutConfirmMessage': 'يمكنك تسجيل الدخول مجددًا برقم هاتفك في أي وقت.',
    'sellerProfile.removeConfirmTitle': 'حذف حسابك؟',
    'sellerProfile.removeConfirmMessage': 'سيؤدي هذا إلى حذف حسابك وجميع إعلاناتك نهائيًا. لا يمكن التراجع عن هذا.',
    'sellerProfile.removeConfirmButton': 'حذف الحساب',
    'sellerProfile.editTitle': 'الملف الشخصي',
    'sellerProfile.updatePhoneTitle': 'تحديث رقم الهاتف',
    'sellerProfile.updatePasswordTitle': 'تحديث كلمة المرور',
    'sellerProfile.linkedAccountsTitle': 'الحسابات المرتبطة',
    'sellerProfile.helpTitle': 'المساعدة والدعم',
    'sellerProfile.termsTitle': 'الشروط والأحكام',

    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.tryAgain': 'حاول مرة أخرى',
    'common.verify': 'تحقق',
    'common.verifying': 'جارٍ التحقق…',
    'common.resendPrompt': 'لم تستلم الرمز؟ أعد الإرسال خلال 0:{seconds}',
    'common.resendCode': 'إعادة إرسال الرمز',
    'common.devHint': 'نسخة تطوير — لا يوجد مزوّد رسائل SMS/واتساب حقيقي. تحقق من طرفية الخادم للحصول على رمزك.',
    'common.verificationCode': 'رمز التحقق',
    'common.sale': 'بيع',
    'common.rent': 'إيجار',
    'common.offline': 'لا يوجد اتصال بالإنترنت',

    'propertyType.Villa': 'فيلا',
    'propertyType.Apartment': 'شقة',
    'propertyType.Commercial': 'محل تجاري',
    'propertyType.Land': 'أرض',
    'amenity.hospital': 'مستشفى',
    'amenity.school': 'مدرسة',
    'amenity.supermarket': 'سوبر ماركت',
    'amenity.mosque': 'مسجد',
    'amenity.busStop': 'موقف حافلات',
    'amenity.gym': 'صالة رياضية',
    'amenity.park': 'حديقة',

    'welcome.headline': 'كفى تصفحًا لإعلانات بعيدة',
    'welcome.subtitle': 'شاهد ما هو معروض للبيع أو الإيجار حيث أنت — اختر نطاق البحث الخاص بك، من بضعة شوارع إلى المدينة بأكملها.',
    'welcome.discover': 'اكتشف العقارات القريبة',
    'welcome.loginSignup': 'تسجيل الدخول / إنشاء حساب',
    'welcome.terms': 'انضمامك يعني موافقتك على شروط الاستخدام وسياسة الخصوصية لدينا.',

    'login.title': 'هل لديك حساب بالفعل؟',
    'login.subtitle': 'أدخل رقم هاتفك للمتابعة.',
    'login.phoneLabel': 'رقم الهاتف',
    'login.phoneHint': 'أدخل رقمك الجزائري المكوّن من 9 أرقام، مثل 0555 12 34 56.',
    'login.passwordLabel': 'كلمة المرور',
    'login.passwordPlaceholder': 'كلمة مرورك',
    'login.forgot': 'نسيت كلمة المرور؟',
    'login.submit': 'تسجيل الدخول',
    'login.submitBusy': 'جارٍ تسجيل الدخول…',
    'login.or': 'أو',
    'login.google': 'المتابعة باستخدام Google',
    'login.noAccount': 'ليس لدي حساب',
    'login.offlineError': 'أنت غير متصل بالإنترنت. اتصل بالإنترنت لتسجيل الدخول.',

    'forgotPassword.phoneTitle': 'ما هو رقمك؟',
    'forgotPassword.phoneSubtitle': 'سنرسل رمزًا إلى رقم هاتف حسابك حتى تتمكن من تعيين كلمة مرور جديدة.',

    'accountType.title': 'هل أنت مشترٍ أم بائع؟',
    'accountType.subtitle': 'سنقوم بإعداد حسابك بالشكل الصحيح.',
    'accountType.buyerTitle': 'مشترٍ',
    'accountType.buyerDescription': 'احفظ المفضلة واجعل البائعين يلاحظونك.',
    'accountType.sellerTitle': 'بائع',
    'accountType.sellerDescription': 'انشر وأدر إعلانات العقارات.',
    'accountType.haveAccount': 'لدي حساب بالفعل',

    'role.title': 'من أنت؟',
    'role.subtitle': 'سنعرض لك الميزات المناسبة لاحتياجاتك.',
    'role.individualTitle': 'فرد',
    'role.individualDescription': 'انشر عقارك الخاص وأدره.',
    'role.agencyTitle': 'وكالة',
    'role.agencyDescription': 'أدر إعلانات متعددة مع شارة موثّقة.',
    'role.pitchTitle': 'قرب حقيقي، دخل حقيقي',
    'role.pitch1': 'انشر في أقل من 3 دقائق',
    'role.pitch2': 'إعلانات مجانية للبدء',
    'role.pitch3': 'تواصل مع الأشخاص القريبين على الفور',
    'role.haveAccount': 'لدي حساب بالفعل',
    'role.switchToBrowsing': 'التبديل إلى التصفح',

    'signupPhone.channelSheetTitle': 'استلام رمزك عبر',
    'signupPhone.sendWhatsapp': 'الإرسال عبر واتساب',
    'signupPhone.sendSms': 'الإرسال عبر رسالة نصية',
    'signupPhone.title': 'ما هو رقمك؟',
    'signupPhone.subtitle': 'يتواصل معك العملاء هنا عبر الاتصال وواتساب. نتحقق أولًا برمز.',
    'signupPhone.submit': 'متابعة',
    'signupPhone.submitBusy': 'جارٍ الإرسال…',
    'signupPhone.label': 'رقم الهاتف (واتساب)',
    'signupPhone.hint': 'أدخل رقمًا جزائريًا من 9 أرقام، مثل 0555 12 34 56.',
    'signupPhone.offlineError': 'أنت غير متصل بالإنترنت. اتصل بالإنترنت للمتابعة.',

    'signupOtp.title': 'أدخل الرمز',
    'signupOtp.subtitlePhone': 'أرسلنا رمزًا مكوّنًا من 6 أرقام إلى هاتفك {phone}',
    'signupOtp.subtitleWhatsapp': 'أرسلنا رمزًا مكوّنًا من 6 أرقام إلى واتساب {phone}',
    'signupOtp.changeNumber': 'تغيير الرقم',

    'signupPassword.title': 'أنشئ كلمة مرور',
    'signupPassword.subtitle': 'ستستخدمها لتسجيل الدخول لاحقًا.',
    'signupPassword.submit': 'تعيين كلمة المرور',
    'signupPassword.setLabel': 'تعيين كلمة المرور',
    'signupPassword.setPlaceholder': '8 أحرف على الأقل',
    'signupPassword.confirmLabel': 'تأكيد كلمة المرور',
    'signupPassword.confirmPlaceholder': 'أعد كتابة كلمة المرور',
    'signupPassword.errorMinLength': 'استخدم {min} أحرف على الأقل.',
    'signupPassword.errorMismatch': 'كلمتا المرور غير متطابقتين.',

    'signupProfile.title': 'أكمل ملفك الشخصي',
    'signupProfile.subtitle': 'يساعدنا هذا على ربطك بالمشترين والمستأجرين المناسبين القريبين منك.',
    'signupProfile.submit': 'متابعة',
    'signupProfile.submitBusy': 'جارٍ إنشاء الحساب…',
    'signupProfile.addAgencyLogo': 'إضافة شعار الوكالة',
    'signupProfile.addProfileImage': 'إضافة صورة شخصية',
    'signupProfile.agencyLogoLabel': 'شعار الوكالة',
    'signupProfile.profileImageLabel': 'الصورة الشخصية',
    'signupProfile.fullNameLabel': 'الاسم الكامل',
    'signupProfile.fullNamePlaceholder': 'مثل: زكرياء لونيس',
    'signupProfile.agencyNameLabel': 'اسم الوكالة',
    'signupProfile.agencyNamePlaceholder': 'مثل: Kniss Realty',
    'signupProfile.monthlyLabel': 'كم عدد العقارات التي تنشرها كل شهر؟',
    'signupProfile.monthlyPlaceholder': '2',
    'signupProfile.termsText': 'أوافق على سياسة الخصوصية وشروط الخدمة',
    'signupProfile.termsA11y': 'الموافقة على سياسة الخصوصية وشروط الخدمة',
    'signupProfile.errorPhotoPermission': 'اسمح بالوصول إلى مكتبة الصور لإضافة صورة.',
    'signupProfile.offlineError': 'أنت غير متصل بالإنترنت. اتصل بالإنترنت للإنهاء.',

    'connectGoogle.title': 'ربط حساب Google',
    'connectGoogle.subtitle': 'سجّل الدخول بشكل أسرع في المرة القادمة. يمكنك تخطي هذا الآن.',
    'connectGoogle.google': 'Google',
    'connectGoogle.connect': 'ربط',
    'connectGoogle.connected': 'مرتبط',
    'connectGoogle.continue': 'متابعة',
    'connectGoogle.skip': 'تخطي',

    'termsScreen.title': 'الشروط والأحكام',
    'termsScreen.body1': 'ستُنشر هنا الشروط الكاملة لخدمة Kniss Go.',
    'termsScreen.body2':
      'هذا التطبيق مشروع طلابي أُنجز لمقياس CM3050 Mobile Development في جامعة لندن. وهو ليس خدمة تجارية فعلية، ولا يجمع أي مدفوعات، ويخزّن الحسابات والإعلانات فقط على خادم تطوير محلي.',

    'radiusPicker.title': 'اكتشف ما حولك',
    'radiusPicker.subtitle': 'حدّد نطاقك، حتى {max}',
    'radiusPicker.searchAround': 'البحث حول',
    'radiusPicker.searchRadiusA11y': 'نطاق البحث',
    'radiusPicker.useCurrentLocation': 'استخدام موقعي الحالي',
    'radiusPicker.chooseNeighborhood': 'اختيار حي',
    'radiusPicker.neighborhoodA11y': 'الحي',
    'radiusPicker.startExploring': 'ابدأ الاستكشاف',
    'radiusPicker.startExploringA11y': 'ابدأ الاستكشاف',

    'scanning.locatingHeadline': 'جارٍ تحديد موقعك...',
    'scanning.locatingSubtitleNeighborhood': 'جارٍ تركيز البحث على {neighborhood}.',
    'scanning.locatingSubtitleGps': 'جارٍ الحصول على إشارة GPS دقيقة للحصول على نتائج صحيحة.',
    'scanning.scanningHeadline': 'جارٍ المسح ضمن {radius} حولك...',
    'scanning.scanningSubtitleNeighborhood': 'جارٍ التحقق مما هو قريب في {neighborhood}.',
    'scanning.scanningSubtitleGps': 'جارٍ التحقق مما هو قريب، مباشرة أثناء تحركك.',
    'scanning.foundHeadlineOne': 'تم العثور على عقار واحد قريب',
    'scanning.foundHeadlineOther': 'تم العثور على {count} عقار قريب',
    'scanning.foundSubtitle': 'جارٍ فتح نتائجك الآن.',
    'scanning.cancel': 'إلغاء',
    'scanning.errorTitle': 'تعذّر تحديد موقعك',
    'scanning.errorLoadFailed': 'تعذّر تحميل العقارات القريبة. حاول مرة أخرى بعد قليل.',
    'scanning.errorOffline': 'أنت غير متصل بالإنترنت. أعد الاتصال لمسح المنطقة المحيطة بك.',
    'scanning.errorNeighborhoodGone': 'هذا الحي لم يعد متاحًا.',
    'scanning.errorLocationDenied': 'اسمح بالوصول إلى الموقع لرؤية ما هو قريب.',
    'scanning.errorLocationRead': 'تعذّرت قراءة موقعك. تأكد من أن خدمة الموقع مفعّلة.',
    'scanning.continueTestLocation': 'المتابعة بموقع تجريبي',
    'scanning.label': 'البحث عن عقارات في [ {place} ]',
    'scanning.nearYou': 'بالقرب منك',

    'results.nothingWithin': 'لا شيء ضمن {radius}',
    'results.tryWidening': 'حاول توسيع نطاقك من الشاشة السابقة.',

    'propertyDetail.boosted': 'مُعزَّز',
    'propertyDetail.postedAgo': 'نُشر قبل {days} يومًا',
    'propertyDetail.showLess': 'عرض أقل',
    'propertyDetail.more': 'المزيد',
    'propertyDetail.sectionInfo': 'معلومات العقار',
    'propertyDetail.type': 'النوع',
    'propertyDetail.landArea': 'مساحة الأرض',
    'propertyDetail.area': 'المساحة',
    'propertyDetail.rooms': 'الغرف',
    'propertyDetail.features': 'المميزات',
    'propertyDetail.utilities': 'المرافق',
    'propertyDetail.floors': 'الطوابق',
    'propertyDetail.parkingSpots': 'أماكن وقوف السيارات',
    'propertyDetail.parkingSpotsValue': '{count} أماكن',
    'propertyDetail.finishing': 'التشطيب',
    'propertyDetail.documents': 'المستندات',
    'propertyDetail.whereYoullBe': 'أين ستكون',
    'propertyDetail.nearbySubtitle': 'كل ما هو قريب ضمن 500 متر.',
    'propertyDetail.close': 'إغلاق',
    'propertyDetail.addFavorite': 'إضافة إلى المفضلة',
    'propertyDetail.removeFavorite': 'إزالة من المفضلة',
    'propertyDetail.viewProfile': 'عرض ملف {name}',
    'propertyDetail.seller': 'البائع',
    'propertyDetail.whatsapp': 'واتساب',
    'propertyDetail.callNow': 'اتصل الآن',
    'propertyDetail.contactWhatsapp': 'التواصل عبر واتساب',

    'propertyCard.areaRooms': '{area} م² · {rooms} غرف',
    'propertyCard.distanceAway': ' · على بعد {distance}',

    'publicProfile.agency': 'وكالة',
    'publicProfile.individualSeller': 'بائع فردي',
    'publicProfile.seller': 'بائع',
    'publicProfile.buyer': 'مشترٍ',
    'publicProfile.otherListings': 'إعلانات أخرى',
    'publicProfile.noOtherListings': 'لا توجد إعلانات نشطة أخرى',

    'favorites.emptyTitle': 'لا توجد مفضلات بعد',
    'favorites.emptyMessage': 'أضف عقارًا إلى المفضلة لحفظه لوقت لاحق. ستجد جميع مفضلاتك هنا.',
    'favorites.startExploring': 'ابدأ الاستكشاف',

    'dashboard.welcomeBack': 'مرحبًا بعودتك',
    'dashboard.defaultName': '',
    'dashboard.activeListings': 'الإعلانات النشطة',
    'dashboard.interestedBuyers': 'المشترون المهتمون',
    'dashboard.expiringSoonSection': 'إعلانات قاربت على الانتهاء',
    'dashboard.nothingExpiring': 'لا شيء ينتهي خلال {days} أيام القادمة.',
    'dashboard.expiringInDays': 'ينتهي خلال {days} يوم',
    'dashboard.interestedBuyersSection': 'المشترون المهتمون',
    'dashboard.noInterestYet': 'لا يوجد اهتمام بعد — يظهر هنا المشترون الذين يضيفون إعلاناتك إلى المفضلة.',
    'dashboard.interestedIn': 'مهتم بـ {title} · {time}',
    'dashboard.yourProperties': 'عقاراتك',
    'dashboard.noPropertiesYet': 'لم تنشر أي شيء بعد.',
    'dashboard.loadErrorTitle': 'تعذّر تحميل لوحة التحكم الخاصة بك',

    'listingPosted.title': 'إعلانك مباشر الآن',
    'listingPosted.active': 'نشط',
    'listingPosted.currentLocation': 'الموقع الحالي',
    'listingPosted.favouriteOne': 'مفضلة',
    'listingPosted.favouriteOther': 'مفضلات',
    'listingPosted.expiresInOne': 'ينتهي خلال يوم واحد.',
    'listingPosted.expiresInOther': 'ينتهي خلال {days} أيام.',
    'listingPosted.seeAnnouncement': 'عرض إعلاني',
    'listingPosted.returnToProperties': 'العودة إلى عقاراتي',

    'propertyList.heading': 'عقاراتك',
    'propertyList.countOne': 'إعلان واحد',
    'propertyList.countOther': '{count} إعلانات',
    'propertyList.searchPlaceholder': 'البحث في إعلاناتك',
    'propertyList.filterA11y': 'تصفية الإعلانات',
    'propertyList.noListingsTitle': 'لا توجد إعلانات بعد',
    'propertyList.noListingsText': 'كل ما تنشره يظهر هنا لإدارته.',
    'propertyList.postListing': 'نشر إعلان',
    'propertyList.nothingMatchesTitle': 'لا توجد نتائج',
    'propertyList.nothingMatchesText': 'لا يوجد إعلان يطابق هذا البحث وهذه الفلاتر.',
    'propertyList.clearSearchFilters': 'مسح البحث والفلاتر',
    'propertyList.loadErrorTitle': 'تعذّر تحميل إعلاناتك',
    'propertyList.interestedBuyerOne': 'مشترٍ مهتم',
    'propertyList.interestedBuyerOther': 'مشترين مهتمين',
    'propertyList.statusActive': 'نشط',
    'propertyList.statusExpiringSoon': 'قارب على الانتهاء',
    'propertyList.statusExpired': 'منتهٍ',
    'propertyList.statusExpiringInDays': 'ينتهي خلال {days} يوم',
    'propertyList.purposeSell': 'بيع',
    'propertyList.purposeRent': 'إيجار',

    'filterSheet.title': 'تصفية',
    'filterSheet.close': 'إغلاق الفلاتر',
    'filterSheet.propertyType': 'نوع العقار',
    'filterSheet.status': 'الحالة',
    'filterSheet.purpose': 'الغرض',
    'filterSheet.clearAll': 'مسح الكل',
    'filterSheet.clearAllA11y': 'مسح جميع الفلاتر',
    'filterSheet.apply': 'تطبيق',
    'filterSheet.applyA11y': 'تطبيق الفلاتر',

    'addProperty.signInTitle': 'سجّل الدخول لنشر إعلان',
    'addProperty.signInMessage': 'التصفح لا يحتاج إلى حساب — لكن لنشر عقار ستحتاج إلى حساب بائع.',
    'addProperty.createSellerAccount': 'إنشاء حساب بائع',
    'addProperty.haveAccount': 'لدي حساب بالفعل',
    'addProperty.buyerAccountTitle': 'هذا حساب مشترٍ',
    'addProperty.buyerAccountMessage':
      'أنت مسجّل الدخول باسم {name}. يمكن لحسابات المشترين التصفح وحفظ المفضلة، لكن نشر الإعلانات يتطلب حساب بائع.',

    'wizard.errorPhotoPermission': 'اسمح بالوصول إلى مكتبة الصور لإضافة صور.',
    'wizard.errorPhotoProcess': 'تعذّرت معالجة إحدى هذه الصور. جرّب صورة أخرى.',
    'wizard.errorLocationPermission': 'اسمح بالوصول إلى الموقع لتحديد مكان هذا العقار.',
    'wizard.errorLocationFailed': 'تعذّر الحصول على موقعك. حاول مرة أخرى بعد قليل.',
    'wizard.offlineError': 'أنت غير متصل بالإنترنت. اتصل بالإنترنت لنشر إعلانك.',
    'wizard.post': 'نشر',
    'wizard.posting': 'جارٍ النشر…',

    'wizard.listingType.title': 'بيع أم إيجار؟',
    'wizard.listingType.subtitle': 'هل تعرض هذا العقار للبيع أم للإيجار؟',

    'wizard.type.title': 'نوع العقار',
    'wizard.type.subtitle': 'اختر ما تنشره — لكل نوع تفاصيله الخاصة.',

    'wizard.about.title': 'أخبر المشترين عن عقارك',
    'wizard.about.subtitle': 'الأساسيات التي يطّلع عليها المشترون أولًا.',
    'wizard.about.titleLabel': 'العنوان',
    'wizard.about.titlePlaceholderVilla': 'مثل: فيلا مع حديقة، حيدرة',
    'wizard.about.titlePlaceholderApartment': 'مثل: F3 مضيئة، باب الزوار',
    'wizard.about.titlePlaceholderCommercial': 'مثل: محل بزاوية، القبة',
    'wizard.about.titlePlaceholderLand': 'مثل: أرض قابلة للبناء، بئر توتة',
    'wizard.about.titlePlaceholderDefault': 'أعطِ إعلانك عنوانًا',
    'wizard.about.descriptionLabel': 'الوصف',
    'wizard.about.descriptionPlaceholder': 'ما الذي يميّزه؟',
    'wizard.about.landAreaLabel': 'مساحة الأرض (م²)',
    'wizard.about.builtAreaLabel': 'المساحة المبنية (م²)',
    'wizard.about.apartmentAreaLabel': 'مساحة الشقة (م²)',
    'wizard.about.areaLabel': 'المساحة (م²)',
    'wizard.about.priceLabel': 'السعر (دج)',
    'wizard.about.negotiabilityLabel': 'قابلية التفاوض',
    'wizard.about.negotiableYes': 'نعم، قابل للتفاوض',
    'wizard.about.negotiableNo': 'لا، سعر ثابت',
    'wizard.about.negotiableExchange': 'يقبل المبادلة',

    'wizard.features.title': 'مميزات العقار ومستنداته',
    'wizard.features.subtitle': 'كل شيء اختياري — أضف ما ينطبق.',
    'wizard.features.floorsLabel': 'عدد الطوابق',
    'wizard.features.apartmentTypeLabel': 'نوع الشقة',
    'wizard.features.roomsLabel': 'عدد الغرف',
    'wizard.features.featuresLabel': 'مميزات العقار',
    'wizard.features.utilitiesLabel': 'المرافق',
    'wizard.features.parkingLabel': 'أماكن وقوف السيارات',
    'wizard.features.finishingLabel': 'التشطيب',
    'wizard.features.documentsLabel': 'مستندات الملكية',
    'wizard.features.choose': 'اختر…',

    'wizard.nearby.title': 'ما هو قريب',
    'wizard.nearby.subtitle': 'كل ما يقع ضمن حوالي 500 متر من العقار.',

    'wizard.photos.title': 'إضافة صور العقار',
    'wizard.photos.subtitle': 'حتى {max}. اضغط × لإزالة إحداها.',
    'wizard.photos.removePhoto': 'إزالة الصورة {n}',
    'wizard.photos.addPhotos': 'إضافة صور',

    'wizard.location.title': 'الموقع',
    'wizard.location.subtitle': 'أين يقع العقار؟',
    'wizard.location.useCurrent': 'استخدام موقعي الحالي',
    'wizard.location.chooseNeighborhood': 'اختيار حي',
    'wizard.location.finding': 'جارٍ تحديد موقعك…',
    'wizard.location.setAt': 'تم التحديد — {lat}, {lon}',

    'wizard.review.title': 'راجع إعلانك',
    'wizard.review.subtitle': 'راجع كل شيء، ثم انشر.',
    'wizard.review.editA11y': 'تعديل {section}',
    'wizard.review.listingTypeSection': 'نوع الإعلان',
    'wizard.review.for': 'من أجل',
    'wizard.review.propertyTypeSection': 'نوع العقار',
    'wizard.review.typeLabel': 'النوع',
    'wizard.review.aboutSection': 'حول العقار',
    'wizard.review.titleLabel': 'العنوان',
    'wizard.review.descriptionLabel': 'الوصف',
    'wizard.review.landAreaLabel': 'مساحة الأرض',
    'wizard.review.priceLabel': 'السعر',
    'wizard.review.negotiabilityLabel': 'قابلية التفاوض',
    'wizard.review.featuresSection': 'المميزات والمستندات',
    'wizard.review.floorsLabel': 'الطوابق',
    'wizard.review.apartmentTypeLabel': 'نوع الشقة',
    'wizard.review.roomsLabel': 'الغرف',
    'wizard.review.featuresLabel': 'المميزات',
    'wizard.review.utilitiesLabel': 'المرافق',
    'wizard.review.parkingLabel': 'أماكن وقوف السيارات',
    'wizard.review.finishingLabel': 'التشطيب',
    'wizard.review.documentsLabel': 'المستندات',
    'wizard.review.nearbySection': 'ما هو قريب',
    'wizard.review.nearbyLabel': 'القريب',
    'wizard.review.noneSelected': 'لم يُحدَّد شيء',
    'wizard.review.photosSection': 'الصور',
    'wizard.review.photosLabel': 'الصور',
    'wizard.review.noneAdded': 'لم تُضَف أي صورة',
    'wizard.review.locationSection': 'الموقع',
    'wizard.review.whereLabel': 'أين',
    'wizard.review.coordinatesLabel': 'الإحداثيات',
    'wizard.review.currentLocation': 'الموقع الحالي',
    'wizard.review.builtArea': 'المساحة المبنية',
    'wizard.review.apartmentArea': 'مساحة الشقة',
    'wizard.review.areaLabel': 'المساحة',

    'linkedAccounts.title': 'الحسابات المرتبطة',
    'linkedAccounts.subtitle': 'أدر طريقة تسجيل دخولك وتأمين حسابك.',
    'linkedAccounts.phoneNumber': 'رقم الهاتف',
    'linkedAccounts.google': 'Google',
    'linkedAccounts.connected': 'مرتبط',
    'linkedAccounts.connect': 'ربط',
    'linkedAccounts.connectA11y': 'ربط حساب Google',
    'linkedAccounts.connecting': 'جارٍ الربط…',
    'linkedAccounts.note': 'تسجيل الدخول يتم برقم الهاتف وكلمة المرور. ربط Google معروض هنا للتوضيح فقط — هذه النسخة ليس بها تسجيل دخول حقيقي عبر Google.',

    'help.title': 'الأسئلة الشائعة',
    'help.subtitle': 'إجابات عن الأسئلة الشائعة حول طريقة عمل Kniss Go.',
    'help.contactButton': 'تواصل عبر واتساب',
    'help.q1': 'هل أحتاج إلى حساب لنشر إعلان؟',
    'help.a1': 'نعم. التصفح متاح للجميع بدون تسجيل دخول، لكن نشر إعلان يتطلب حساب بائع مجاني — فردي أو وكالة.',
    'help.q2': 'كم من الوقت يبقى الإعلان نشطًا؟',
    'help.a2': '30 يومًا من تاريخ نشره. بعد ذلك يظهر كمنتهٍ في تبويب عقاراتك.',
    'help.q3': 'ماذا يحدث عندما يضيف أحدهم إعلاني إلى المفضلة؟',
    'help.a3': 'تتم مشاركة رقم هاتفه معك كمشترٍ مهتم — ستراه في لوحة التحكم الخاصة بك وعلى ذلك الإعلان. لا شيء لفتحه، ولا رسوم.',
    'help.q4': 'هل يمكنني تعديل أو حذف إعلان بعد نشره؟',
    'help.a4': 'ليس بعد — ميزة التعديل والحذف قادمة لاحقًا. حاليًا يبقى الإعلان نشطًا حتى انتهاء مدته البالغة 30 يومًا.',
    'help.q5': 'كيف أغيّر رقم هاتفي أو كلمة المرور؟',
    'help.a5': 'من الملف الشخصي ← تحديث رقم الهاتف أو تحديث كلمة المرور. يرسل كلاهما رمزًا من 6 أرقام للتأكد من هويتك قبل أي تغيير.',
    'help.q6': 'هل هناك أي تكلفة لاستخدام Kniss Go؟',
    'help.a6': 'لا. النشر والمفضلة وجهات اتصال المشترين المهتمين كلها مجانية. لا توجد إعلانات مدفوعة أو ترقيات أو اشتراكات.',
    'help.q7': 'من يرى إعلاني من المشترين؟',
    'help.a7': 'يبحث المشترون ضمن نطاق يحددونه، مركّز على موقعهم. يظهر إعلانك لأي شخص يصل نطاقه إلى موقعه.',

    'updatePasswordOtp.title': 'تأكيد أنه أنت',
    'updatePasswordOtp.subtitle': 'أرسلنا رمزًا مكوّنًا من 6 أرقام إلى واتساب {phone}. أدخله لتغيير كلمة مرورك.',

    'updatePasswordForm.title': 'تحديث كلمة مرورك',
    'updatePasswordForm.subtitle': 'اختر كلمة مرور جديدة لتسجيل الدخول.',
    'updatePasswordForm.newPasswordLabel': 'كلمة المرور الجديدة',
    'updatePasswordForm.confirmLabel': 'تأكيد كلمة المرور الجديدة',
    'updatePasswordForm.submit': 'تأكيد كلمة المرور',
    'updatePasswordForm.submitBusy': 'جارٍ الحفظ…',
    'updatePasswordForm.errorMinLength': 'استخدم {min} أحرف على الأقل.',
    'updatePasswordForm.errorMismatch': 'كلمتا المرور غير متطابقتين.',
    'updatePasswordForm.offlineError': 'أنت غير متصل بالإنترنت. اتصل بالإنترنت للمتابعة.',

    'updatePhone.title': 'تحديث رقم هاتفك',
    'updatePhone.subtitle': 'أدخل رقمك الحالي ورقمك الجديد.',
    'updatePhone.currentLabel': 'رقم الهاتف',
    'updatePhone.newLabel': 'رقم الهاتف الجديد',
    'updatePhone.hint': 'أدخل رقمًا جزائريًا من 9 أرقام، مثل 0555 12 34 56.',
    'updatePhone.sendWhatsapp': 'الإرسال عبر واتساب',
    'updatePhone.sendSms': 'الإرسال عبر رسالة نصية',
    'updatePhone.sending': 'جارٍ الإرسال…',
    'updatePhone.errorSame': 'هذا رقمك الحالي بالفعل.',
    'updatePhone.offlineError': 'أنت غير متصل بالإنترنت. اتصل بالإنترنت للمتابعة.',

    'updatePhoneCode.title': 'أدخل الرمز',
    'updatePhoneCode.subtitlePhone': 'أرسلنا رمزًا مكوّنًا من 6 أرقام إلى هاتفك {phone}',
    'updatePhoneCode.subtitleWhatsapp': 'أرسلنا رمزًا مكوّنًا من 6 أرقام إلى واتساب {phone}',

    'updateSuccess.phoneTitle': 'تم تحديث رقم الهاتف بنجاح!',
    'updateSuccess.phoneMessage': 'تم تحديث رقم هاتفك. يمكنك الآن استخدام رقمك الجديد للتحقق من الحساب والإشعارات.',
    'updateSuccess.passwordTitle': 'تم تحديث كلمة المرور بنجاح!',
    'updateSuccess.passwordMessage': 'تم تغيير كلمة مرورك. يمكنك الآن استخدام كلمة مرورك الجديدة لتسجيل الدخول بأمان.',
    'updateSuccess.goToSettings': 'الذهاب إلى الإعدادات',

    'editProfile.errorPhotoPermission': 'اسمح بالوصول إلى مكتبة الصور لتغيير صورتك.',
    'editProfile.changePhoto': 'تغيير صورة الملف الشخصي',
    'editProfile.fullNameLabel': 'الاسم الكامل',
    'editProfile.agencyNameLabel': 'اسم الوكالة',
    'editProfile.phoneLabel': 'رقم الهاتف',
    'editProfile.phoneHint': 'غيّره من تحديث رقم الهاتف — يبقى موثّقًا برمز.',
    'editProfile.save': 'حفظ',
    'editProfile.saving': 'جارٍ الحفظ…',
    'editProfile.offlineError': 'أنت غير متصل بالإنترنت. اتصل بالإنترنت للحفظ.',

    'favoritePrompt.title': 'أنشئ حسابًا مجانيًا لحفظ العقارات',
    'favoritePrompt.message': 'سجّل الدخول أو أنشئ حساب مشترٍ للاحتفاظ بمفضلاتك ومتابعة ما توقفت عنده.',
    'favoritePrompt.notNow': 'ليس الآن',
    'favoritePrompt.continue': 'تسجيل الدخول / إنشاء حساب',

    'photoGallery.photo': 'صورة',
    'photoGallery.photoOfA11y': 'الصورة {index} من {total}',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en');
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    async function loadStoredLanguage() {
      try {
        const stored = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
        if (stored) {
          setLanguageState(stored);
        }
      } catch (error) {
        console.log('Failed to load stored language', error);
      } finally {
        setIsReady(true);
      }
    }
    loadStoredLanguage();
  }, []);

  async function setLanguage(code) {
    const target = LANGUAGES.find((entry) => entry.code === code);
    if (!target) return;

    await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, code);
    setLanguageState(code);

    // RTL is a native layout-direction flag, not something React can
    // hot-swap: it only takes effect after the JS bundle reloads.
    const needsRTLChange = target.isRTL !== I18nManager.isRTL;
    if (needsRTLChange) {
      I18nManager.allowRTL(true);
      I18nManager.forceRTL(target.isRTL);
      try {
        await Updates.reloadAsync();
      } catch (error) {
        // Updates.reloadAsync needs a built app or dev client: it can
        // no-op in plain Expo Go. Worth testing on a real device, not just here.
        console.log('Could not auto-reload for RTL change', error);
      }
    }
  }

  // params interpolates `{name}`-style placeholders into the translated
  // string, e.g. t('scanning.scanningHeadline', { radius: '500 m' }).
  function t(key, params) {
    const raw = translations[language]?.[key] ?? translations.en[key] ?? key;
    if (!params) return raw;
    return Object.keys(params).reduce(
      (result, paramKey) => result.split(`{${paramKey}}`).join(params[paramKey]),
      raw
    );
  }

  // Property type is a small, fully-controlled set (Villa/Apartment/
  // Commercial/Land), so this translates reliably — but an older or
  // otherwise unrecognised value falls back to itself rather than showing
  // a raw, untranslated dictionary key like "propertyType.Studio".
  function tType(type) {
    const key = `propertyType.${type}`;
    const label = t(key);
    return label === key ? type : label;
  }

  const value = {
    language,
    setLanguage,
    t,
    tType,
    isRTL: LANGUAGES.find((entry) => entry.code === language)?.isRTL ?? false,
    languages: LANGUAGES,
  };

  if (!isReady) {
    return null;
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside a LanguageProvider');
  }
  return context;
}
